import { type WorkflowAction } from 'src/modules/workflow/workflow-executor/workflow-actions/types/workflow-action.type';
import { type WorkflowTrigger } from 'src/modules/workflow/workflow-trigger/types/workflow-trigger.type';

export type WorkflowTemplateKey =
  | 'RESEARCH_BRIEF'
  | 'FOLLOW_UP_DIGEST'
  | 'ACCOUNT_MONITORING';

export type WorkflowTemplateDefinition = {
  key: WorkflowTemplateKey;
  name: string;
  description: string;
  trigger: WorkflowTrigger;
  steps: WorkflowAction[];
};

// What an installable application supplies (Phase 5). id / valid /
// nextStepIds are optional here and generated by
// normalizeWorkflowTemplateSteps — a WorkflowAction requires all three, and a
// stored step missing them fails at execution, not at insert.
export type WorkflowStepInput = Omit<
  WorkflowAction,
  'id' | 'valid' | 'nextStepIds'
> &
  Partial<Pick<WorkflowAction, 'id' | 'valid' | 'nextStepIds'>>;

export type WorkflowDefinitionInput = {
  name: string;
  description?: string;
  trigger: WorkflowTrigger;
  steps: WorkflowStepInput[];
};
