import { Field, InputType } from '@nestjs/graphql';

import {
  IsArray,
  IsBoolean,
  IsObject,
  IsOptional,
  IsString,
} from 'class-validator';
import GraphQLJSON from 'graphql-type-json';

@InputType()
export class InstallWorkflowDefinitionInput {
  @Field(() => String)
  @IsString()
  name: string;

  @Field(() => String, { nullable: true })
  @IsOptional()
  @IsString()
  description?: string;

  // Structurally a WorkflowTrigger; typed as JSON on the wire because the
  // union is server-internal, exactly as createWorkflowVersionStep already
  // accepts step definitions as JSON today.
  @Field(() => GraphQLJSON)
  @IsObject()
  trigger: Record<string, unknown>;

  // Entries need only {type, name, settings}: id, valid and nextStepIds are
  // generated by normalizeWorkflowTemplateSteps.
  @Field(() => GraphQLJSON)
  @IsArray()
  steps: Record<string, unknown>[];

  @Field(() => Boolean, { defaultValue: true })
  @IsBoolean()
  activate: boolean;
}
