apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searmcrm-server-pvc
  namespace: searmcrm
spec:
  storageClassName: default
  volumeName: searmcrm-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
