apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searmcrm-docker-data-pvc
  namespace: searmcrm
spec:
  storageClassName: default
  volumeName: searmcrm-docker-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
