apiVersion: v1
kind: PersistentVolume
metadata:
  name: searmcrm-server-pv
  namespace: searmcrm
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
