apiVersion: v1
kind: Service
metadata:
  name: searmcrm-db
  namespace: searmcrm
spec:
  internalTrafficPolicy: Cluster
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: searmcrm-db
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
